# Use Python 3.9 image
image: python:3.9

# Cache pip dependencies
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONPATH: "$CI_PROJECT_DIR"

cache:
  paths:
    - .cache/pip

stages:
  - test
  - build
  - deploy

# Setup virtual environment and install dependencies
before_script:
  - python --version
  - pip --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest ruff
    - pwd
    - ls -la
    - ruff check .
    - pytest tests/ -v
  tags:
    - docker

build:
  stage: build
  script:
    - echo "Building the project"
    - mkdir -p dist
    - tar -czvf dist/omics_oracle.tar.gz omics_oracle run_gradio_interface.py requirements.txt
  artifacts:
    paths:
      - dist/*
  only:
    - main
  tags:
    - docker

# Optionally add documentation generation if needed
pages:
  stage: build
  script:
    - echo "Generating documentation"
    # Add commands to generate your documentation, if applicable
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker

# Placeholder for deployment script
deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
  tags:
    - docker